clc;
close all;
clear all;
fm=input('Enter Frequency of the message signal: ');
fc=input('Enter Frequency of the carrier signal: ');
fs=100*fc;
t=0:1/fs:((2/fm)-(1/fs));
x=0.4*cos(2*pi*fm*t)+0.5;
y=modulate(x,fc,fs,'ppm');
xrec=demod(y,fc,fs,'ppm');
subplot(2,2,1);
plot(x);
title('Message Signal');
subplot(2,2,2);
plot(y);
axis([0 500 -0.2 1.2]);
title('PPM');
subplot(2,2,3);
plot(xrec);
title('PPD');
